# Generated by Django 3.0.3 on 2020-02-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Costumer'),
        ),
    ]
